### ISSUE TITLE
Add options for better management of page history

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#109]
You can enable page history in Content, and then a previous version gets stored in the database.
However there is no limit to the history and no easy way of smart clearing.
- Add an option to store only the last X versions and clear earlier versions
- Add a way to remove old versions based on date or so many version back. 

The history table can grow quite a lot when you build a lot in Content.

**Comment by Guite** [comment]
This could be done as general functions for the generator cc @gfr

**Comment by Guite** [comment]
We need to think about this carefully with regards to how the incremental updates work.

**Comment by Guite** [comment]
This functionality has been added.
