### ISSUE TITLE
Wrong page loads randomly when caching enabled

### ISSUE THREAD

**Issue by robbrandt** [zikula-modules/Content#111]
I have this problem on three different servers, all using Content 4.0.1 from July 2012 I think, and Zikula 1.3.x.  This is the only module I see it on.

What I see when this happens, I have page D and page N.  When I use the URL for page N, Page D loads sometimes.  Not all the time.  Sometimes page N does load.  Never any other pages besides D or N.  It only seems to happen when there are a large number of Content pages active.  I've personally not observed it loading by mistake a NEWER page than the one it should, it always seems to be an older one, and I've not seen "contemporary" pages mixed up - in other words, the older one was many ID numbers less.  At one time we thought that perhaps it was loading page not where page ID = N, but the page that contained Block ID N (which happened to be page ID D), but i just observed a page where this was not the case (it was one off, Block ID N was in Page ID C).

In the previous 2 sites that exhibited this behavior we turned caching off and the problem went away.  Short URLs are turned OFF on these sites, FWIW.

In the one I found today, caching must stay on for performance reasons, but Page D was optional so I disabled it.  The problem has gone away for now.  Short URLs are turned ON on this site, FWIW.

My theory is that there is a bug in the code that generates the cached file and it produces the wrong page.  Zikula uses that cached page until the cache expires and then generates a new one, which may or may not be the right page.

**Comment by robbrandt** [comment]
Resurrecting this issue. We have a site where performance is an issue and we'd love to turn render caching on.

I currently can't reproduce this issue but it was showing when we first set up this site, so "off" went render caching.  I was hoping today that I could reproduce it on my workstation and trace it through the debugger.  But, no.

I did turn rendering off on the live site for a bit and all seemed to work well, but when an admin is logged in I am getting an error message that could give a clue:

&lt;div id="z-maincontent" class="z-module-content"&gt;&lt;iv id="page4" class="z-content-page"&gt;
    
WARN (4): E_WARNING: current() expects parameter 1 to be array, null given in Smarty.class.php line 1901 &lt;br /&gt;
WARN (4): E_WARNING: next() expects parameter 1 to be array, null given in Smarty.class.php line 1902 &lt;br /&gt;


&lt;div class="content-pageinfo"&gt;

On these pages where the error shows, the Content page editing toggle is non-responsive. Turn off rendering, or not logged in, no error message.  Lines 1901 & 1902 both use $_cache_attrs in function &_smarty_cache_attrs so this is highly suspect.

In the 2 years since I've opened this issue I have come to believe, rightly or wrongly, that the issue is caching of content blocks not the whole content page itself.  FWIW.

**Comment by robbrandt** [comment]
Using 1.3.9 and Content 4.01.

**Comment by robbrandt** [comment]
I have a new site I am working on that is Content heavy, so I became motivated to debug this.  I don't understand the cache system well but I think I have found the problem and solution.  Please indulge my wordiness.  This is using Zikula 1.3.10 and Content 4.10.

First, to understand the Content module cache file structure, I observe that two types of pages are cached; pages and content blocks.  For each of these, the record ID is used as a cache_id, and when the cache files are saved they are structured in directories according to cache_id/type/cachefile.tpl.  So, for example a content page with ID 110 would be cached at ztemp/view_cache/Content/110/user/page--t_Theme-l_en.tpl and if that page has an html block in it with ID 315 it would be cached at ztemp/view_cache/Content/315/content_type/html_view--t_Theme-l_en.tpl.  Well, this is what's SUPPOSED to happen, anyway.

On enabling caching and viewing a few pages (which showed the first page (110) correctly, but continued to show that same page when other pages were selected) I observed that Content/110/user/ directory was empty, as was the corresponding /user/ directories for the other pages.  Looking through the cache files actually generated, I found the 110 page cached at Content/315/user/.  I do not have a page with ID 315.  Looking at the actual page layout, it happens that content block 315 is the last block on page 110.  Checking the other pages I was trying to view, the pattern was similar.  The page cache was being saved in the directory for the last block on the page, not the page itself.

Attempting to confirm this was the problem, I physically moved the page cache files to the directories I thought they were supposed to be in, and viewed the pages in a browser; they worked!

Next, stepping through the code for the view function in a debugger, the relevant section is here:
https://github.com/zikula-modules/Content/blob/master/lib/Content/Controller/User.php#L96
On line 96, the cache_id is properly set to 110.  However, by the time it finished executing L132 (api getPage), cache_id changes to 315.  Which surprises me, because I would think $this would be out of scope for anything done by the api call.  But that's what it's doing.

In version 4.10, $this isn't used between L99 and L140, so my fix is simply to move that block of code to AFTER the getPage api call.  It seems to work.  I see in the main branch of current code there is other stuff, so it may or may not be so simple.  I haven't analyzed it.

I haven't put this into production yet pending comments from others that know better than me.  Comments?

**Comment by Guite** [comment]
Thanks Rob for debugging this problem. Yes I think your suggestion makes sense. :+1:

**Comment by robbrandt** [comment]
Just discovered more caching issues.  A minor one is that the blue (i) editing control doesn't show up when caching is turned on.  A more significant one is that we use Multihook on these pages, and when caching is turned on the hook code shows up not the content it should be showing.

**Comment by Guite** [comment]
Closing since Content 5.0 uses Twig only so Smarty caching isn't relevant anymore.
