### ISSUE TITLE
Deletion of Tags for a page failed without a reply

### ISSUE THREAD

**Issue by Portugao** [zikula-modules/Content#128]
If I try to delete a tag, the tag (Module 'Tag') will not be deleted.
I get no error message.

I tried with News and it works so it is an issue of Content I think.

**Comment by Guite** [comment]
Closing as "won't fix / worksforme" since Content 5.0.0 uses the new hooks systems and an entirely rewritten codebase. Also Tag module needs to be migrated to Zikula 2 before any new tests can be made with regards to it's functionality.
