### ISSUE TITLE
Add youtube thumbnail image choice

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#140]
See this topic for the various options of the thumbnail:
http://stackoverflow.com/questions/2068344/how-to-get-thumbnail-of-youtube-video-link-using-youtube-api

What Asaph said is right. However every YouTube video does not have all 9 thumbnails. But there are default 07 thumbnails for every video. They are: (Image size depends on video.) 

Player Background Thumbnail (480x360px) :

http://i1.ytimg.com/vi/HIrMIeN5ttE/0.jpg
Normal Quality Thumbnail (120x90px) :
http://i1.ytimg.com/vi/HIrMIeN5ttE/default.jpg
Medium Quality Thumbnail (320x180px) :
http://i1.ytimg.com/vi/HIrMIeN5ttE/mqdefault.jpg
High Quality Thumbnail (480x360px) :
http://i1.ytimg.com/vi/HIrMIeN5ttE/hqdefault.jpg
Start Thumbnail (120x90px) :
http://i1.ytimg.com/vi/HIrMIeN5ttE/1.jpg
Middle Thumbnail (120x90px) :
http://i1.ytimg.com/vi/HIrMIeN5ttE/2.jpg
End Thumbnail (120x90px) :
http://i1.ytimg.com/vi/HIrMIeN5ttE/3.jpg

And additionally next two thumbnails may or may not exist. For HQ videos they exist.
Standard Definition Thumbnail (640x480px) :

http://i1.ytimg.com/vi/HIrMIeN5ttE/sddefault.jpg
Maximum Resolution Thumbnail (1920x1080px) :
http://i1.ytimg.com/vi/HIrMIeN5ttE/maxresdefault.jpg

More info on obtaining details via JS function:
http://www.techtweaker.com/retrieve-youtube-video-details-using-javascript/

Or this github age for API samples.

**Comment by Guite** [comment]
Using the `hqdefault` one in Content 5.0.0 - the other ones are not generally usable since they are very small unfortunately.
