### ISSUE TITLE
Add plugin options and layout for Bootstrap (3) output

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#142]
Zikula Core 1.3.7 will be focussing towards jQuery and Bootstrap 3

Themes and layouts are also going towards BS3 a lot.

The option to have layouts use BS3 grid:
http://getbootstrap.com/css/#grid

And extend the html block (or adding a plugin) to generate BS3 CSS/Components
- http://getbootstrap.com/components/
- http://getbootstrap.com/css

**Comment by espaan** [comment]
A lot of things can go via plugins for scribite like
http://ckeditor.com/addon/ckeditorbootstraputils

**Comment by Guite** [comment]
The new layout concept is entirely focused on BS grids, see #209.

Closed.
