### ISSUE TITLE
Migrate Content to Bootstrap / jQuery

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#146]
Convert styling and JS where necessary to Bootstrap and jQuery, since that will be the Core 1.4.x way to go anyways.
- [x] Convert pageedit drag&drop to jQueryUI portlet.
- [ ] Convert pagelist page drag&drop to jsTree jquery plugin.
- [ ] Convert the other parts to jQuery
- [ ] Make Bootstrap 3 column layouts available

Only in 1.4.x core
- [x] Convert contextmenus to jQuery something, via Core

**Comment by espaan** [comment]
page edit is done, pagelist been looking into it, but needs work, all the other code just needs some TLC :-)

A bootstrap layout version I will make the coming months with a switch in the backend probably. I need it for a Bootstrap converted site anyways.

**Comment by robbrandt** [comment]
@espaan I see in the commit log that there have been some bootstrap additions.  Is bootstrap now **required**? I am going to attempt to use 4.21 on a zk1.3.x site; I have seen the notes that it _should_ work.

**Comment by Guite** [comment]
Pagelist is part of the generated code (based on jsTree).
All JS will be based on jQuery in 5.0, too.
The new layout concept (see #209) will entirely be adapted to Bootstrap capabilities.

Closing.
