### ISSUE TITLE
Improve YouTube plugin (html5 usage, new options)

### ISSUE THREAD

**Issue by Guite** [zikula-modules/Content#157]
Now that YouTube started using HTML5 per default we should do this, too.
I had changed it for certain projects already so I have reference code available.

**Comment by espaan** [comment]
Yes indeed. flash based stuff can be gone totally for me as well. Can you add some reference code in the ticket ? Just makes it easier to implement :-)

**Comment by Guite** [comment]
Instead of an `<object>` there is just an `<iframe>`.
This is the official code shown for embedding:
```
<iframe width="{$width}" height="{$height}" src="https://www.youtube.com/embed/{$videoId}" frameborder="0" allowfullscreen></iframe>
```

In addition I use two parameters for hiding related videos and enforce autoplay (both options would be reasonable additions for the content type):
```
<iframe width="{$width}" height="{$height}" src="https://www.youtube.com/embed/{$videoId}?feature=player_detailpage&amp;rel=0&amp;autoplay=1" frameborder="0" allowfullscreen></iframe>
```

**Comment by espaan** [comment]
re=0 is hide related and autoplay=1 you mean ? Of course that's good to add

**Comment by Guite** [comment]
Yes. We should make this configurable for each single video to make it really usable.

**Comment by Guite** [comment]
Changed title accordingly.

**Comment by espaan** [comment]
:+1:

**Comment by espaan** [comment]
GIve it a try and see if all works, in my local test it works

**Comment by Guite** [comment]
Great stuff :+1:  Will test it next week (no chance before).

**Comment by Guite** [comment]
Thanks, Erik!

**Comment by espaan** [comment]
I should make a version release as well. the whole new page edit jQ stuff etc and all the fixes and small improvements.

**Comment by craigh** [comment]
don't forget to add the ExtensionsLibrary stuff before your release and then release using the EL!

**Comment by espaan** [comment]
Nope, that's also a very good reason to release and test EL

**Comment by craigh** [comment]
be sure to [push the big green button](http://zikula.org/library/) before you tag your release at github.
