### ISSUE TITLE
Children of menu 'pagelists' contains wrong urls if shorturls enabled

### ISSUE THREAD

**Issue by Portugao** [zikula-modules/Content#158]
For example:
Link Sitemap gives this url:
domain/content/content/sitemap

Zikula 1.3.9
Content 4.1.0

**Comment by espaan** [comment]
Hi, I just tested with my local install 1.3.9 and current Git content (4.2.0) and there the url becomes http://localhost/zk139/index.php/content/sitemap with shorturls enabled.
It's the default shorturls enabled. 

And you mean this menu right ?
![greenshot_2015-02-03_09-43-10](https://cloud.githubusercontent.com/assets/349093/6016970/21faf6f4-ab89-11e4-9f6a-41937f883cfb.jpg)

**Comment by Portugao** [comment]
Yes, i speak of this menu.
Will have a look on actaul repository.

**Comment by Portugao** [comment]
Actual repository checked.
It works with shorturls enabled only correctly, if i strip entrypoint and set to not show the module name for Content in the shorturl settings.

**Comment by Guite** [comment]
Content 5.0.0 uses Symfony routing where this problem won't occur anymore. Closing.
