### ISSUE TITLE
Hide option for duplication translations on non-multilingual sites

### ISSUE THREAD

**Issue by Guite** [zikula-modules/Content#159]
If a site does not use multiple languages the checkbox `duplicate also translations` is confusing and should be hidden.

**Comment by espaan** [comment]
Hi, is this on page copying ?

**Comment by Guite** [comment]
Yep.

**Comment by espaan** [comment]
Are the translation parts on content items also showing when multilingual is disabled ? 
Then those parts should be hidden as well.

**Comment by Guite** [comment]
Thanks.
