### ISSUE TITLE
front page setting in 1.4.0 invalid

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Content#160]
something is going wrong if you configure zikula 1.4.0 to have content at front page

**Comment by espaan** [comment]
As far as I can see its a core issue in legacy router 

> 
> something is going wrong if you configure zikula 1.4.0 to have content at front page
>

**Comment by craigh** [comment]
ping @cmfcmf

**Comment by craigh** [comment]
if this is a core issue, the ticket should be there...

**Comment by craigh** [comment]
Since Content still has core_max = 1.3.99 then it is technically, not compatible.

**Comment by craigh** [comment]
`Content/user/extlist` works fine for me (after changing core_max for Content)

**Comment by rallek** [comment]
for me is doing extlist as well. 

But I want to have an explicit page e.g. pid=2 as the output of content. How do I do that? That seems to be broken

**Comment by craigh** [comment]
My point is thaw at it works for the module so it must not be a core problem

**Comment by espaan** [comment]
It does not work for Content, as I described in Slack already I think he argument pid=x is not passed along.

I can say already that the arguments are not passed on to Content and Content says then page is not there. Arguments as in pid=1 I mean
On this line 
https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/CoreBundle/EventListener/LegacyRouteListener.php#L96 the module is called without arguments for newType (not sure what is newType here) and that does not work with arguments that determine the page to show. When I add $arguments there it works fine.

If news works that could be, but it's only a non core problem if the argument part is also used and works :-)

**Comment by craigh** [comment]
if it is a core problem, close this ticket and open one in the core or it will be forgotten

**Comment by espaan** [comment]
Done see https://github.com/zikula/core/issues/2293

**Comment by espaan** [comment]
@rallek can you test as well the fix: https://github.com/zikula/core/issues/2293#issuecomment-77521903

**Comment by craigh** [comment]
I tested it and it worked for me.

**Comment by rallek** [comment]
@espaan as craigh already said. It works! Great!

**Comment by espaan** [comment]
Great Thanks
