### ISSUE TITLE
Pageinfo control has caching issue

### ISSUE THREAD

**Issue by robbrandt** [zikula-modules/Content#164]
Now that I have caching working reliably on Content, I am seeing other issues.  It seems that things that shouldn't be cached ARE being cached, even when a {nocache} tag surrounds them.  In particular, the blue (i) pageinfo control that should show up for edit permissioned users.

Steps to reproduce:
Log in as administrator
Turn on caching
Delete all existing cached and compiled files
View a Content page (using /content/view/pid/{id}/ for convenience)
- it should show the pageinfo control.
  Change the URL to /content/view/pid/{id}/preview/1/ to put it into preview mode
- it should NOT show the pageinfo control.  So far so good...
  go back to /content/view/pid/{id}/
- problem!  it's not showing the control.  The value of $preview seems to stick.
  change it to /content/view/pid/{id}/editmode/1/
- Edit mode does seem to work
  revert again to content/view/pid/{id}/
- pageinfo still not showing up.  It seems the only way to get it back is to flush the cache.

You would think that fix would be to add {nocache} tags to the page info code, but they are there already in /Content/templates/user/pageinfo.tpl.

Any ideas?

**Comment by espaan** [comment]
Hi Rob,
I think nocache does not always do the right thing. Do you have theme caching or render caching on ?

**Comment by robbrandt** [comment]
Hi, thanks.  The above behavior happens with render caching turned on.  None of the other options are selected.

**Comment by Guite** [comment]
Closing since Content 5.0 uses Twig only so Smarty caching isn't relevant anymore.
