### ISSUE TITLE
Missing install documentation

### ISSUE THREAD

**Issue by squidjam** [zikula-modules/Content#167]
Tried to install the Content module with Zikula 1.4.1 by uncompressing the zip file into the modules folder, refreshed the extensions module list page and it's not listed.

Is there something else that needs to be done to install it (and should be documented in a readme or install file)?

**Comment by Guite** [comment]
Can you please retest using Zikula 1.4.3-dev from http://ci.zikula.org/job/Zikula_Core-1.4.3/ ? It should work (at least it does for me) now.
