### ISSUE TITLE
Content type for Media Module

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Content#175]
Media Module should only have clean future code. Might be someone is able to create a contettype inside Content to manage the time until Content is transfered to the future code as well and Media Module is able to provide the contenttype itself.

Here you have the related ticket at Media Module: https://github.com/cmfcmf/MediaModule/issues/2

**Comment by Guite** [comment]
Closing. The media module needs to provide this when the Content 5.0 release is available.
