### ISSUE TITLE
context menus are broken when using zikula1.4.4build156

### ISSUE THREAD

**Issue by MrMontesa** [zikula-modules/Content#176]
I just upgraded my testbed to Zikula 1.4.4build156 and started app testing.
For content I recognized that I cant edit any pages any longer. Tried the following 2 ways:
a) sign in, access a content page, click on the small blue "i" icon. The expected context menu does not show up.
b) sign in, access admin backend and choose Content module to get the content pages overview. By default cascaded pages are collapsed and have to be extended by clicking the small plus sign.
On clicking the plus button  nothing happens.

This behavior can be seen on my public testbed. Happy to help to resolve this issue.
Thanks much

Edit:
Also saw that some other functions do not work any longer. For example clicking the green dot in order to deactivate a form.

**Comment by Guite** [comment]
Seems like a JavaScript error is happening. Can you try setting `zikula_asset_manager.combine` to `false`? This should probably fix it for the meanwhile.

**Comment by MrMontesa** [comment]
Unfortunately doesnt make a difference. It was set to false from the beginning. Tries setting it to true, deleting cache, and back to false (with deleting cache) but doesnt help.

**Comment by Guite** [comment]
Weird. Content works fine on a site I am currently building.

**Comment by MrMontesa** [comment]
I'm not too sure which version I'm using but gess the master from this repo. In extensions menue the version is labled as 4.2.1.
If you have a better resource to use, let me know and I'm happy to test this version.
You can check my testbed if you'd like top see the issue in real life...

**Comment by Guite** [comment]
I am also using the master revision. You may mail me some credentials for your site, then I can check tomorrow probably.

**Comment by MrMontesa** [comment]
Cool, credentials are still the same. Sent them again via slack. Thanks for your help.

**Comment by Guite** [comment]
Somehow your page does not include the `/modules/Content/javascript/ajax.js` file. Sorry I couldn't find the reason for this.

**Comment by MrMontesa** [comment]
Hmm, I think its related to the newly re-added Formicula content plugin. Just did a fresh install added Content and it was working. When adding a Formicula form to a content page it stops working.
Same applies for admin-panel-menue. Does not pop out either.

Secondly I recognized that Contents context menue now looks different. Seems like the small icons are not loaded any longer.
actual behavior:
![content-context-menue-no-icons](https://cloud.githubusercontent.com/assets/600125/20826787/a8121ae0-b86d-11e6-815a-fde5b1883daf.png)

versus expected:
![content-context-menue-with-icons](https://cloud.githubusercontent.com/assets/600125/20826795/b36da86e-b86d-11e6-868b-c0b8601dd51f.png)

**Comment by Guite** [comment]
>  Hmm, I think its related to the newly re-added Formicula content plugin.
> When adding a Formicula form to a content page it stops working.
Can't confirm this from the site I am currently working on.

> Secondly I recognized that Contents context menue now looks different.
Looks like a similar problem. Probably the `/modules/Content/style/style.css` file isn't loaded.

**Comment by MrMontesa** [comment]
Keep in mind that I was able to reproduce this issue here on a fresh install, while the other one referenced focuses on Upgraded page!

**Comment by Guite** [comment]
Closed in favour of https://github.com/zikula-modules/Profile/issues/62
