### ISSUE TITLE
Integrating Custom Content Type

### ISSUE THREAD

**Issue by robbrandt** [zikula-modules/Content#178]
So I've just written a custom content type that fetches data from our CiviCRM membership management application via an API, so that it can be displayed within a Content block/page.

I integrated it by hacking the Content module files, because I didn't see an obvious way of adding it to the list of active types. I simply added it to the list of types in Content/lib/Content/Util.php function getTypes().

Is there a better way?

**Comment by Guite** [comment]
Use an event handler in another module. See Formicula, SimpleMedia or MOST modules for examples.
