### ISSUE TITLE
Moving items results in an error

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Content#181]
In zk 1.4.5 this feature is working fine, but not in 1.4.6:
If I move one item of the exanple page delivered with content leads to this errormessage
![grafik](https://cloud.githubusercontent.com/assets/935250/22704554/67404e6c-ed68-11e6-8a23-669bdcf2f58b.png)
The item seems to be moved after clicking ok. But save & view shows nothing changed.

**Comment by Guite** [comment]
reverted

**Comment by Guite** [comment]
I still suspect that in 1.4.6 the csrf check now works also for places where it did not correctly work before. Which means that the correct fix would be adding correct tokens to the ajax requests which currently not carry a csrf token.

**Comment by Guite** [comment]
I assume this because of the session refactoring.

**Comment by Guite** [comment]
Actually this is a duplicate of https://github.com/zikula/core/issues/3450

**Comment by rallek** [comment]
This problem is back in 1.4.6 stable

**Comment by Guite** [comment]
Fixed in https://github.com/zikula-modules/Content/commit/e1c0adcb49d657a3fe17971e912141459be4e679 and https://github.com/zikula/core/commit/344033b402f7ad15d8af76684666bc67337544c7
