### ISSUE TITLE
Module Activation with Zikula 1.4.6 not possible

### ISSUE THREAD

**Issue by AlexL777** [zikula-modules/Content#183]
Hello Developers,

Unfortunately, I can not activate the content module under Zikula 1.4.6 and an error message is generated immediately.

Could you please update this module again for Zikula 1.4.6 or check it with you.

The module "News" can not be activated under Zikula 1.4.6.

I want to install just a few modules and I noticed that.

Thanks in advance.

**Comment by craigh** [comment]
Hi @AlexL777 thank you for trying Zikula!  I'm sorry you are having trouble with some modules.

> error message is generated immediately.

can you provide the error?

**Comment by AlexL777** [comment]
`Error! Table creation failed for content_page SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'content_page' already exists. Failing Query: "CREATE TABLE content_page (page_id INT NOT NULL AUTO_INCREMENT, page_ppid INT DEFAULT '0' NOT NULL, page_title VARCHAR(255) NOT NULL, page_showtitle TINYINT DEFAULT '1' NOT NULL, page_urlname VARCHAR(255) NOT NULL, page_metadescription LONGTEXT NOT NULL, page_metakeywords LONGTEXT NOT NULL, page_nohooks TINYINT DEFAULT '0' NOT NULL, page_layout VARCHAR(100) NOT NULL, page_categoryid INT DEFAULT '0', page_views INT DEFAULT '0', page_active TINYINT DEFAULT '1' NOT NULL, page_activefrom DATETIME, page_activeto DATETIME, page_inmenu TINYINT DEFAULT '1' NOT NULL, page_pos INT DEFAULT '0' NOT NULL, page_level INT DEFAULT '0' NOT NULL, page_setleft INT DEFAULT '0' NOT NULL, page_setright INT DEFAULT '0' NOT NULL, page_language VARCHAR(10), page_optString1 VARCHAR(255) NOT NULL, page_optString2 VARCHAR(255) NOT NULL, page_optText LONGTEXT NOT NULL, page_obj_status VARCHAR(1) DEFAULT 'A' NOT NULL, page_cr_date DATETIME DEFAULT '1970-01-01 00:00:00' NOT NULL, page_cr_uid INT DEFAULT '0' NOT NULL, page_lu_date DATETIME DEFAULT '1970-01-01 00:00:00' NOT NULL, page_lu_uid INT DEFAULT '0' NOT NULL, PRIMARY KEY(page_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = innodb"
Initialization of Content failed!`

Database tables for the module seem to exist. I have the content module simply uploaded to the directory **/modules** and then in the back end of Zikula 1.4.6 want to activate. Then came this error.

**Comment by craigh** [comment]
sounds like maybe you attempted to install twice. please delete tables that begin with `content_` and then try again

**Comment by craigh** [comment]
I sent you a slack invitation

**Comment by AlexL777** [comment]
`Error in DBUtil::executeSQL: INSERT INTO content_page (page_title,page_urlname,page_layout,page_setleft,page_setright,page_language,page_cr_date,page_cr_uid,page_lu_date,page_lu_uid) VALUES ('Content introduction page','content-introduction-page','Column2d6238',0,1,'en','2017-02-21 23:19:54',2,'2017-02-21 23:19:54',2)
SQLSTATE[HY000]: General error: 1364 Field 'page_metadescription' doesn't have a default value`

Thanks for Slack and I will gladly accept it.

Deleting the old database tables unfortunately brought nothing, so I have completely reinstalled Zikula.

But now I get to see the above error message.

What can it mean? I just clicked on the icon "Install" in the backend.

**Comment by craigh** [comment]
I'm hoping @Guite will have some ideas. He's on your timezone, so he will probably get back to you tomorrow ;-)

**Comment by AlexL777** [comment]
Ok, let's do this. Thank you!

Also a tip when Zikula runs on the root server under Centos 7. I have to restart after deleting the old database tables "MariaDB" with "service mariadb restart". Otherwise, the backend of Zikula shows that the tables of the database are already double.

This is what I found out today.

**Comment by Guite** [comment]
Hi @AlexL777 

Content is a legacy module which needs a rewrite and has some problems with newer database settings unfortunately. Can you please check your database configuration whether it has the `STRICT_TRANS_TABLES` setting activated? If yes, please deactivate this to probably fix this error.

**Comment by Guite** [comment]
@AlexL777 did that solve the issue?

**Comment by AlexL777** [comment]
On the managed server under Ubuntu most of the Plugin installation worked. Thank you.
