### ISSUE TITLE
moving items leads to an error.

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Content#185]
#181 is back. But more observations wich might be helping to find the bug:

If I switch ``debug: true`` in ``custom_parameters.yml`` the edit layout of content is broken suddenly. The background is transparent and the layout is using 100% of the page.

I am using content 4.2.2 from date 7th of February 2017. Core is 1.4.6 stable

**Comment by espaan** [comment]
Hi Ralf, for me the moving worked with current Content and 146. Do you have Content in a subfolder installed ? That does not work for me. I have to move the installation to the root folder for the ajax calls to be working.

**Comment by rallek** [comment]
Hi Erik, thanks for feedback. In my case it is installed in the root of 2017.pggo.de. So this should not be the Problem.

**Comment by rallek** [comment]
Strange. On another test site, also 1.4.6, Content is working fine. Have to look what is the difference.

**Comment by Guite** [comment]
Fixed in https://github.com/zikula-modules/Content/commit/e1c0adcb49d657a3fe17971e912141459be4e679 and https://github.com/zikula/core/commit/344033b402f7ad15d8af76684666bc67337544c7

**Comment by rallek** [comment]
Great! Thanks!
