### ISSUE TITLE
MySQL 5.7 compatibility

### ISSUE THREAD

**Issue by robbrandt** [zikula-modules/Content#187]
MySQL 5.7 requires columns to have default values unless NULL is allowed.  I am starting to find issues related to this in existing modules.  To get around them I usually just allow nulls on the field, but there might be code elsewhere that presumes an empty value.  Here are the issues I am finding for Content.

When creating a new content page
content_page.page_metadescription, fixed by allowing null.
content_page.page_metakeywords, fixed by allowing null.
content_page.page_optString1, fixed by allowing null.
content_page.page_optString2, fixed by allowing null.
content_page.page_optText, fixed by allowing null.

When adding a new content item
content_content.con_styleclass, fixed by allowing null.

I will update as/if I find more

**Comment by Guite** [comment]
Fixed in Content 5.0 which is properly using Doctrine now.
