### ISSUE TITLE
This module will be modified with Zikula 1.5.0

### ISSUE THREAD

**Issue by AlexL777** [zikula-modules/Content#188]
Hello Developers,

I wanted to inquire whether I can use this module for Zikula 1.5.0? Where can I get Content 5.0.0? Here in the releases it is not yet.

Thanks in advance.

![zikula_content_module-zikula-1-5-0-wishes](https://user-images.githubusercontent.com/7885632/27983200-f120705c-63b6-11e7-99ed-e0cc376fed6c.jpg)

**Comment by Guite** [comment]
Content 5.0.0 is to be started asap at https://github.com/zikula-modules/Content/tree/5.0.0/

It will support Zikula 2.0.x.
