### ISSUE TITLE
Content 5.0.0 - Integration capabilities and interfaces

### ISSUE THREAD

**Issue by Guite** [zikula-modules/Content#194]
- [x] Tagged services for content types; migrate existing ones
- [x] Migrate setting for permission inheritance
- [x] Categories
- [x] PDF support (added in model)
- [x] Settings for hooks subscribers integration (per page).
- [x] Also content items should be able to call hook subscribers (#77) (editing, display)
- [x] Migrate blocks
- [x] Scribite plugins (for CKEditor, Quill, Sommernote, TinyMCE) (#33)

**Comment by rallek** [comment]
In the past we have been able to add a node of the content tree in menutree. That was a great combination. Can this be done some how again? May be in the current menu module?
