### ISSUE TITLE
give the pages the "own" option

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Content#202]
Please add for the pages entity ``ownerPermission true``

For community sites like my church site or my classic car site the usage of the content module can be done by several peoples. There it would be nice if they can change only their "own" pages. 

Not needed to manage it also for the sub pages. So each single page do have an owner. Sub pages might have other owners than their parents.

**Comment by Guite** [comment]
Implemented in d153c3d5eb50437d84bb8c64c16bfe3e4bdc9fb6
