### ISSUE TITLE
MenuModule Option

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Content#203]
In the past in menutree it was possible to add a node of content page at any place of the menutree tree. All Content pages with the option "show in menu" have been shown in the rendered menu.

A similar option for the current MenuModule would be great. I use it on my church site heavily. I want to restart that site with new ContentModule based on ZK2.x

I place the issue here because this must be done somehow together with the ContentModule development.

**Comment by rallek** [comment]
Is it just a simple route?

**Comment by Guite** [comment]
Implemented in https://github.com/zikula-modules/Content/compare/9b6bed701a903771ee20a283215aec65b0c2300c...11f204d743b0d8593baee8ec4b9e860c71b6daec

See https://github.com/zikula-modules/Content/tree/5.0.0#integration-with-menu-module for the details.

Requires this core change: https://github.com/zikula/core/compare/f6b1638292862976de392a391cda94fcc2068992...e467e23ddff317abe47661df2c9bb88357a70a9c
