### ISSUE TITLE
Content-Detail Block does not show sections

### ISSUE THREAD

**Issue by DirkThiele** [zikula-modules/Content#267]
I've created a page with 1 section and HTML Text inside of it.

In the detail view of the page everything is being displayed as expected.

Putting the same page into a Content-Detail Block then there is only the title of the page shown but not the section with its content.

Content 5.0.0 / Zikula 2.0.10 / Symfony 3.4.14 / PHP 7.2.7-nmm1

Also tried it with a leaflet map in a different page with same effect.

New Zikula installation without any changes to the standard settings after installation.

**Comment by Guite** [comment]
Well, in most cases it is not desired to show a whole page in a block.
The block uses the `views/External/Page/display.html.twig` template. You could simple include the full page template like this:
```
{{ include('@ZikulaContentModule/Page/display.html.twig', {page: page, routeArea: ''}) }}
```

I am not sure what this template should contain by default though.

**Comment by DirkThiele** [comment]
Do you mean replacing the content of `views/External/Page/display.html.twig`

with this?

`{{ include('@ZikulaContentModule/Page/display.html.twig', {page: page, routeArea: ''}) }}`

When I do so I get an error message that says:

`ContextErrorException Twig_Error_Runtime
HTTP 500 Internal Server Error
An exception has been thrown during the rendering of a template ("Notice: Undefined index: _zkModule").`

I tried to find out what needs to be added to the code in order to get it running but I'm totally lost.

**Comment by rallek** [comment]
Can we have both templates? The one with only title ist the Default one, and the other one with füll Content can be used by overwriting inside the block configuration.

**Comment by Guite** [comment]
An additional setting or a separate template seems overkill. We will just add the required template code, but comment it out by default. Going to do that tomorrow.

**Comment by Guite** [comment]
Added example in 073fba5fc97bb62f4c9a9d829bed95f43bf531a2

Closing.
