### ISSUE TITLE
MenuModule integration

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Content#296]
reading this: https://github.com/zikula-modules/Content#menumodule
Menu Module id two level only. I created a three level menu via Content site structe:
![grafik](https://user-images.githubusercontent.com/935250/44980982-99205b80-af71-11e8-88b0-a6a6601719df.png)

How should I manage this?

**Comment by Guite** [comment]
I do not understand the issue.

**Comment by craigh** [comment]
https://github.com/zikula/core/blob/master/src/docs/Admin/NavBarMenu.md#drop-menu

bootstrap does not support multi-level menus.

**Comment by rallek** [comment]
I am looking for a solution how to manage this issue. Here a scenario:
I do have a situation where 4 levels of content pages are available. 
The root of these 4 levels should appear in the site menu. There only level 1 and 2 should appear (due to bootstrap limitation). Opening a level 2 page I want to add a menu item on that page with the starting point of this page. So I do have a second menu on that page where I can access the next two levels.

In this case all pages are menu relevant. But how to tell the root node only to show up with two levels? For the content plugin we can configure this behavior.

**Comment by rallek** [comment]
Might be you can add an option ``b`` e.g. ``ContentPages_2b`` for bootstrap limitation in MenueModule

**Comment by Guite** [comment]
This should be a core issue.

**Comment by Guite** [comment]
Hm...

**Comment by Guite** [comment]
I am not sure about this. When you add `ContentPages` on 2nd level, you would need `ContentPages_1b`. Maybe we can find a better (more flexible) approach.

**Comment by rallek** [comment]
is something possible like this?
![grafik](https://user-images.githubusercontent.com/935250/45087395-fa793380-b105-11e8-8379-755be291f29e.png)

**Comment by Guite** [comment]
Added in https://github.com/zikula-modules/Content/commit/03d7fd84f7c8153cf90d2c2c4b1b4a028cd3f075

**Comment by Guite** [comment]
Added a missing check in https://github.com/zikula-modules/Content/commit/9ccbd1c294a21016ba78850f23c1f971c0d801bb

**Comment by Guite** [comment]
> bootstrap does not support multi-level menus

For reference: there are numerous extensions available which add that functionality.

I just implemented a three-level menu for a project using http://kybarg.github.io/bootstrap-dropdown-hover/ for example.
