### ISSUE TITLE
Author Information Plugin improvement

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Content#298]
Feature request: 
Please make the Avatar picture scalable:
![grafik](https://user-images.githubusercontent.com/935250/45088240-b2a7db80-b108-11e8-9a78-8d24cb21c239.png)
We do need the bigger avatar pictures. It is no solution to upload smaler one.

**Comment by Guite** [comment]
Do you really need a bigger picture in the edit form?

As for the display view, you can change this in the template.

Change `<p class="avatar">{{ userAvatar(author.uid, {rating: 'g'}) }}</p>` to for example `<p class="avatar">{{ userAvatar(author.uid, {rating: 'g', width: 500, class: 'my-image'}) }}</p>`

The class argument is to avoid `img-responsive img-thumbnail` (which is the default class).

**Comment by rallek** [comment]
No, we do need the bigger picture in profile-module :-). My users want to have it there a bit bigger than the past.

My Feature request is regarding the content plugin. If it is an ``about`` page it might be fine to have it bigger than the usual small picture. Changing it in the template it is always the same size.

At the end it is a feature request. If it is to much work I will change the template (same I will do with the history listing)
