### ISSUE TITLE
Using Scribite not possible

### ISSUE THREAD

**Issue by Portugao** [zikula-modules/Content#300]
If I try to edit a page in pages with Scribite I get an error in the console:
```
Laden fehlgeschlagen für das <script> mit der Quelle "domain/web/modules/zikulacontent/js/ZikulaContentModule.Finder.js". 14:40
Laden fehlgeschlagen für das <script> mit der Quelle "domain/web/modules/zikulacontent/scribite/CKEditor/zikulacontentmodule/plugin.js?t=I3I8". 14:1
[Mitteilungsdetails anzeigen/ausblenden] Error: [CKEDITOR.resourceManager.load] Resource name "zikulacontentmodule" was not found at "/web/modules/zikulacontent/scribite/CKEditor/zikulacontentmodule/plugin.js?t=I3I8".
```

**Comment by Portugao** [comment]
maybe, there is something wrong with my update....

**Comment by Portugao** [comment]
Have to check..

**Comment by Guite** [comment]
You need to make web and web/modules writeable

**Comment by Portugao** [comment]
Other modules are writing their datas into the web folder?!

**Comment by Guite** [comment]
Basically content does the same as every most module, copying required scribite plugin files into web/modules/abc. Background is that Scribite expects everything living within web.

**Comment by Portugao** [comment]
Hmmhmm..made a fresh install and it does not work. Tried with 5.0 beta3 and Zikula 2.0.11.

**Comment by Guite** [comment]
> They have 775 rights
Depending on the owning user, the user running the webserver, and the groups of both it could be required to use 777.

If it still does not work ping me in Slack.

**Comment by Guite** [comment]
Refs https://github.com/zikula/core/issues/3804

**Comment by Guite** [comment]
Background was that Content was placed in an incorrect/unintended directory. Moving it into `modules/Zikula/ContentModule/` and updating the meta data by calling the extensions list fixed the problem.

**Comment by Guite** [comment]
Further treatment in https://github.com/Guite/MostGenerator/issues/1202

**Comment by Guite** [comment]
Another improvement has been done in https://github.com/zikula-modules/Content/commit/20ccad792b319e329921d977347d0498c6b37617
