### ISSUE TITLE
Improve responsive palette behaviour

### ISSUE THREAD

**Issue by Guite** [zikula-modules/Content#303]
Currently the palette gets a fixed position when scrolling down to keep visible. This is not responsive though.

Maybe we should switch to using a modal with tabs like Visual Composer for WordPress does it.

cc @rallek 

![grafik](https://user-images.githubusercontent.com/277531/46208533-51e87900-c32b-11e8-8e94-13f2ad4df4bb.png)
![grafik](https://user-images.githubusercontent.com/277531/46208538-57de5a00-c32b-11e8-8c8b-3fe54ff50088.png)
![grafik](https://user-images.githubusercontent.com/277531/46208572-72183800-c32b-11e8-937a-11a98fdc66e7.png)

**Comment by rallek** [comment]
modal would be better I guess
Current solution is not easy to use. I some situations (screen sice, scrolling) it is a mess.
