### ISSUE TITLE
Feature request - query arguments supported

### ISSUE THREAD

**Issue by DirkThiele** [zikula-modules/Content#307]
Hi,
I have added content ot type "Controller" in the ContentModule (5.0.1). 

Controller: `MyModule:MyEntity:view`
Function arguments: `sort=''&sortdir=asc&pos=1&num=0&tpl=Categories`

My assumption was that with the tpl variable I will be able to load a customised template but it seem that it is not being recognised.

Do you think this is something worth to realise?

**Comment by Guite** [comment]
Please try this:

1. Apply 94b9e372a66a9f7f73f2543e80298a69df75dfe6
2. Put `sort=''&sortdir=asc&pos=1&num=0` into the `Request attributes` field
3. Put `tpl=Categories` into the `GET parameters` field

**Comment by DirkThiele** [comment]
Works perfectly fine!

The possibility for adding parameters like `tpl` or `own` is a great benefit!

Thank you!

**Comment by Guite** [comment]
Closed as this is done.
