### ISSUE TITLE
can not choose a Content page in another language within a Scribite editor

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Content#328]
- My site is running English and German.
- Using Scribite
- my current language is German
- I am e.g. in an HTML block and want to add a Content page with its English slug. But I only can choose the German one
![grafik](https://user-images.githubusercontent.com/935250/52879587-ce0b1e00-315f-11e9-9057-866a6e220491.png)

**Comment by rallek** [comment]
of course I can switch my site to English and add than the English link.

**Comment by Guite** [comment]
Please explain which use case requires linking to content in another language.

**Comment by rallek** [comment]
In my case it is the footer of a page. There I have implemented for each language an own html block. From ther I link to privacy police, imprint and contact in its own language (and some specific things of that site)

**Comment by rallek** [comment]
It is not a big thing, just comfort

**Comment by Guite** [comment]
Strictly this is not specific to content then, but a general feature request for scribite plugins in the generator for all entities with translatable slugs. Right?

**Comment by rallek** [comment]
If that part is comming directly from the generator, yes.

**Comment by Guite** [comment]
Yes it does.

**Comment by Guite** [comment]
Added reference https://github.com/Guite/MostGenerator/issues/1215

**Comment by Guite** [comment]
implemented in #504
