### ISSUE TITLE
Scribite editor plugins for selecting links to Content pages

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#33]
Like CoType: a popup where you select a page and then it pastes a link into the HTML code (maybe even using a special syntaxt that allows for post-processing where the current page title is inserted in the link).

-- orig 12 by Jorn Wildt

Changed 2 years ago by hilope

Cc hilope added
comment:2 Changed 20 months ago by herr.vorragend

Milestone set to unassigned
comment:3 Changed 19 months ago by rallek

Cc rallek added
If the logic of needles by multihook is used but a linkd is included (instead the needle syntax) it will do the trick.
comment:4 Changed 13 months ago by espaan

Or a plugin like the one for pagesetter could be used. Shouldn't be that hard I hope.
comment:5 follow-up: ↓ 6 Changed 9 months ago by espaan

Milestone changed from unassigned to 4.0.0
in the current code there is a way provided, see also #137, you can use the following in teh code, there is however no scribite plugin for that.
[[link-CONTENT_ID|some link title]] or [[link-CONTENT_ID]]
comment:6 in reply to: ↑ 5 Changed 9 months ago by rallek

Replying to espaan:
there is however no scribite plugin for that.
But exactly that is the feature request ;-)
comment:7 Changed 8 months ago by espaan

Milestone changed from 4.0.0 to 4.1.0
Indeed :-D Will put it to 410, since 400 is intended to be a fully functional Content in the zk1.3 codebase. Enhancements come after that.

**Comment by Guite** [comment]
Content 5.0 includes/provides plugins for CKEditor, Quill, Sommernote, TinyMCE. Will be reviewed/checked as part of #194.
