### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by shoshia** [zikula-modules/Content#333]
versions 5.0.1-5.0.3

> Doctrine Exception: Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE zikula_content_page (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, workflowState VARCHAR(20) NOT NULL, title VARCHAR(255) NOT NULL, showTitle TINYINT(1) NOT NULL, metaDescription VARCHAR(255) NOT NULL, skipHookSubscribers TINYINT(1) NOT NULL, layout LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', views INT NOT NULL, active TINYINT(1) NOT NULL, activeFrom DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', activeTo DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', inMenu TINYINT(1) NOT NULL, optionalString1 VARCHAR(255) NOT NULL, optionalString2 VARCHAR(255) NOT NULL, optionalText TEXT NOT NULL, stylingClasses LONGTEXT DEFAULT NULL COMMENT '(DC2Type:simple_array)', currentVersion INT DEFAULT 1 NOT NULL, contentData LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', translationData LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', slug VARCHAR(255) NOT NULL, lft INT NOT NULL, lvl INT NOT NULL, rgt INT NOT NULL, root INT DEFAULT NULL, createdDate DATETIME NOT NULL COMMENT '(DC2Type:datetime)', updatedDate DATETIME NOT NULL COMMENT '(DC2Type:datetime)', createdBy_id INT DEFAULT NULL, updatedBy_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_3915731DBF396750 (id), UNIQUE INDEX UNIQ_3915731D989D9B62 (slug), INDEX IDX_3915731D727ACA70 (parent_id), INDEX IDX_3915731D3174800F (createdBy_id), INDEX IDX_3915731D65FF1AEC (updatedBy_id), INDEX workflowstateindex (workflowState), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'zikula_content_page' already exists' while executing DDL: CREATE TABLE zikula_content_page (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, workflowState VARCHAR(20) NOT NULL, title VARCHAR(255) NOT NULL, showTitle TINYINT(1) NOT NULL, metaDescription VARCHAR(255) NOT NULL, skipHookSubscribers TINYINT(1) NOT NULL, layout LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', views INT NOT NULL, active TINYINT(1) NOT NULL, activeFrom DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', activeTo DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', inMenu TINYINT(1) NOT NULL, optionalString1 VARCHAR(255) NOT NULL, optionalString2 VARCHAR(255) NOT NULL, optionalText TEXT NOT NULL, stylingClasses LONGTEXT DEFAULT NULL COMMENT '(DC2Type:simple_array)', currentVersion INT DEFAULT 1 NOT NULL, contentData LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', translationData LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', slug VARCHAR(255) NOT NULL, lft INT NOT NULL, lvl INT NOT NULL, rgt INT NOT NULL, root INT DEFAULT NULL, createdDate DATETIME NOT NULL COMMENT '(DC2Type:datetime)', updatedDate DATETIME NOT NULL COMMENT '(DC2Type:datetime)', createdBy_id INT DEFAULT NULL, updatedBy_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_3915731DBF396750 (id), UNIQUE INDEX UNIQ_3915731D989D9B62 (slug), INDEX IDX_3915731D727ACA70 (parent_id), INDEX IDX_3915731D3174800F (createdBy_id), INDEX IDX_3915731D65FF1AEC (updatedBy_id), INDEX workflowstateindex (workflowState), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
Initialization of ZikulaContentModule failed!

and in DB tables I see ZikulaContentModule and ZikulaProfileModule..Profile module is not installed at all

p.s.
similar error occures when installing Profile

**Comment by Guite** [comment]
See Slack.
