### ISSUE TITLE
sth saved when clicking cancel

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#34]
if you click add module display for example and then you click cancel and nothing was entered - the content element is created.
i think if you do not enter anything in the new content type and click cancel afterwards the element should be deleted.

-- orig 14 by quan

Changed 20 months ago by herr.vorragend

Milestone set to unassigned
comment:2 Changed 19 months ago by rallek

Cc rallek added
comment:3 Changed 13 months ago by espaan

Milestone changed from unassigned to 3.2.0
So very true. Cancel should not create anyting in my opinion as well.
comment:4 Changed 13 months ago by espaan

It is difficult to implement, since the "create" function is actually just the edit function. Clicking on cancel is then the same as not changing an already existing content item. So could be proven hard to get right.
comment:5 Changed 12 months ago by espaan

Milestone changed from 3.2.0 to 3.2.1
I think this will be too hard to get in now. It really requires some rewrite, so I shift it to 3.2.1 to look at later. 
comment:6 Changed 8 months ago by espaan

Milestone changed from 3.2.1 to 4.1.0
Since it requires a workflow change relayed to 410

**Comment by Guite** [comment]
This problem is not applicable anymore, since 5.0 follows an entire new UI concept for page editing.
