### ISSUE TITLE
Permissions in Content Menu Block

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#40]
I am using the Content Menu Block as a hierarchical menu for my site. I would like to be able to set permissions so that I can use the permissions to determine which groups can or cannot see specific menu selections. As an example, I would like members of our organization to be able to see the minutes of past meetings but would like to make sure that non-members to do not see the minutes.
Website: www.tebrotherhood.org
In advance, thank you,
Stephen

--orig 70 by cheshire

Changed 20 months ago by herr.vorragend

Milestone set to unassigned
comment:2 Changed 19 months ago by rallek

Cc rallek added
I have a workaround: Use menutree and call the content node you want. Documentation inside the content.php of menutree
With menutree you can control the menu permissions.
This is only an optical workaround, because the useres can call the id of every content page. The permissions of content need a renew at all...
comment:3 Changed 8 months ago by espaan

Milestone changed from unassigned to 4.1.0
comment:4 Changed 8 months ago by espaan

The latest Menutree does have a plugin option to supply data from modules. Not sure if Content is already in there. Otherwise that might be the way to go, since the menutree menus are much more powerful then the menu in Content.

**Comment by Guite** [comment]
New menu block will only show pages the current user may read.
Will be reviewed/checked as part of #194.
