### ISSUE TITLE
List/evaluation by category irregular

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#43]
When listing Content pages by category within a Content page using the Module display function a pager will appear with the number of items not identical with the actual number (like six items instead of four) and also offering a second page when there are no items on it.
Probably in relation to this another weird appearance: I created a special page template only active for Content pages belonging to a certain category. After the sixth page of that category, further pages show in the regular template, although category settings are identical. Preview shows the page in the correct template, but the real view shows it in the default template. This problem can be seen here:
 http://dl7und.net/sd/txwz/index.php?module=Content&func=view&pid=3
The first six items work correctly, following items (from the list at the bottom) suddenly use the default template. I think this correlates to the first problem because the number of items shown on the first page (before I removed the pager from the template) was six, like the number of items working correctly.

-- orig 82 by dl7und

**Comment by Guite** [comment]
Closing since Content 5.0.0 is a complete rewrite where this behaviour doesn't identically happen.
