### ISSUE TITLE
Permissions on a item by item basis

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#44]
Allow fine grained permissions control so that permissions can be granted to edit say, all html text items, but not other items. 
Attachments
- \- orig 99 by halbrooktech

Change History
comment:1 Changed 13 months ago by espaan

Isn't this possible already with the
'content:plugins:content' => 'Content type name::'
? I haven't tried, so not sure about it. It seems in the code that his permission is not taken into acount with newcontent and editcontent
comment:2 Changed 13 months ago by halbrooktech

If it is, then I'm not sure how to do it, and it's not well documented that I can see. I'd love to allow the staff to edit HTML & YouTube? entries, but not sure how to do that right. 
comment:3 Changed 9 months ago by espaan

Hi, I think this should be possible. The code below is from the contentapi.php. The filename of the plugin, so html for the HTML text content item and youtube for the YoutTube? plugin should work as far as i can see.
                    if (preg_match('/^([-a-zA-Z0-9_]+).php$/', $filename, $matches)) {
                        $contentTypeName = $matches[1];
                        // check permissions for this contentType plugin
                        if (SecurityUtil::checkPermission('content:plugins:content', $contentTypeName . '::', ACCESS_READ)) {
                            $plugins[] = pnModAPIFunc($module['name'], 'contenttypes', $contentTypeName, null);
                        }
                    }
                }

**Comment by Guite** [comment]
Indeed it looks like this is already possible. Closing.
