### ISSUE TITLE
Use same dropdown menus as admin panel

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#50]
The dropdown menus that are in the new admin panel would be a welcome change to the menus in Content. 

-- orig 142by halbrooktech

Attachments
■menuexample.jpg  (20.4 KB) - added by halbrooktech 13 months ago. 
This is the menu I'm talking about. Looks cleaner/better IMHO 
■menuproblem13.jpg  (97.7 KB) - added by halbrooktech 13 months ago. 
Menu Problem in current 1.3 SVN with Current Content SVN 
Change History
comment:1 Changed 13 months ago by espaan 
What are those btw :-) You mean the admin panel in zk1.3 ? and then what dropdowns?
Could you elaborate a little more on what is in there and what functionality you would like
in Content for that part?

Extending usability and look&feel is important with this kind of "should be easy to use" module.

Last edited 13 months ago by espaan (previous) (diff) 
Changed 13 months ago by halbrooktech 
■attachment menuexample.jpg  added 
This is the menu I'm talking about. Looks cleaner/better IMHO

comment:2 Changed 13 months ago by halbrooktech 
<div id="control_contextmenu"...> Is how it's termed in the code best I can tell. The existing menu is also displaying out of place when clicking on the arrow, even in Seabreeze.

Changed 13 months ago by halbrooktech 
■attachment menuproblem13.jpg  added 
Menu Problem in current 1.3 SVN with Current Content SVN

comment:3 Changed 13 months ago by espaan 
Thanks for adding the screenshots. I will try it in seabreeze as well and see what happens. And the current is a bit flat indeed :-)

comment:4 Changed 8 months ago by espaan 
■Milestone changed from unassigned to 4.1.0 
There is ticket with patch in the core about the contextmenu positioning ( http://code.zikula.org/core/ticket/2544). If that is solved then this positioning is also solved. Since the contextmenu is just a Core feature.

About the layouts of the contextmenu, have to check. Maybe Carsten can take a look

**Comment by Guite** [comment]
Content 5.0 will use Bootstrap dropdowns which are now the de-facto standard.
