### ISSUE TITLE
Add GeoCoding to the googlemap plugin location specification

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#53]
--orig 151 by espaan

phenomenon¶
Making a googlemap content item requires clicking on the exact location where you want the map to show. A more convenient way would be to allow entering an address and translate that into the lat and long values.
See  http://code.google.com/apis/maps/documentation/javascript/services.html#Geocoding

reason¶
usability of the googlemap plugin

recommendation¶
Add an option of some sort in the edit section of the googlemap plugin to choose between lat/long coordinates or an address.

Attachments

Change History
comment:1 Changed 8 months ago by espaan 
    ■Milestone changed from 4.0.0 to 4.1.0

**Comment by Guite** [comment]
Closing as "won't fix". Rather than introducing google maps specific vendors we should aim on removing the google specific stuff and rely on Leaflet only. Because leaflet supports different map providers, see https://leaflet-extras.github.io/leaflet-providers/preview/
