### ISSUE TITLE
Update the googlemaps api stuff to PHP class php-google-map-api

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#55]
--orig 155 by espaan

phenomenon¶
There is a PHP class for handlgin with the Googlemaps api. This might be more convenient than using the JS api directly. 

reason¶
Simpler usage of the googlemaps JS api

recommendation¶
Check out the PHP class and see if it helps for the map code.
 http://code.google.com/p/php-google-map-api/

Attachments

Change History
comment:1 Changed 8 months ago by espaan 
    ■Milestone changed from 4.0.0 to 4.1.0

**Comment by Guite** [comment]
Closing as "won't fix". Rather than introducing google maps specific vendors we should aim on removing the google specific stuff and rely on Leaflet only. Because leaflet supports different map providers, see https://leaflet-extras.github.io/leaflet-providers/preview/
