### ISSUE TITLE
Add a field to the googlemaps plugin for choosing a custom marker icon

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#56]
--orig 156 by espaan

phenomenon¶
The current googlemaps plugin uses the standard marker for display of the chosen location. It would be more usable to have a field to optionally choose your own image for the marker icon

reason¶
Get your own marker into the map instead of the default one.

recommendation¶
Check out the googlemaps api JS v3 on how to get a personal maker inthere.
 http://code.google.com/apis/maps/documentation/javascript/overlays.html#Icons

var image = 'beachflag.png'; 
  var myLatLng = new google.maps.LatLng(-33.890542, 151.274856); 
  var beachMarker = new google.maps.Marker({ 
      position: myLatLng, 
      map: map, 
      icon: image 
  });

Attachments

Change History
comment:1 Changed 8 months ago by espaan 
    ■Milestone changed from 3.2.1 to 4.1.0

**Comment by Guite** [comment]
Closing as "won't fix". Rather than introducing google maps specific vendors we should aim on removing the google specific stuff and rely on Leaflet only. Because leaflet supports different map providers, see https://leaflet-extras.github.io/leaflet-providers/preview/
