### ISSUE TITLE
Add Smugmug plugin

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#59]
--orig 179 by espaan

phenomenon¶
Missing Smugmug plugin

reason¶
Smugmug is being used in the field as well, one of the better photo storages

recommendation¶
Just like phpFlickr make a smugmug plugin. the Api looks very similar, since phpSmug ( http://phpsmug.com/) is based upon phpFlickr when it started.

**Comment by Guite** [comment]
Closing as won't fix. A content type for Smugmug or other photo services should be provided by a media module.

Similarly the Flickr and FlashMovie content types won't be migrated to 5.0 as well.
