### ISSUE TITLE
Make category option in admin setting dynamic with JS

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#61]
--orig 202 by espaan

phenomenon¶
In the admin settings the category usage can be set to 2 categories, 1 category or none. 
It would be nice if none is chosen, then also the property for the categogories are both hidden. Same for 1 category, then only the first category registry option should be shown.

reason¶
Simpler admin settings. Only show what is needed. 

recommendation¶
Add JS to hide/show the category properties

Attachments

Change History
comment:1 Changed 5 months ago by craigh 
    ■Milestone changed from 4.0.0 to 4.1.0 
■Status set to pending-review 
Because categories are not properly implemented in Content. I will move this to a later milestone. this may become moot when and if categories are properly implemented.

ref ticket #233

comment:2 Changed 5 months ago by espaan 
    It is BTW only really minor :-)

**Comment by Guite** [comment]
These settings are gone in Content 5.0. Instead categories are added/edited/configured using category registries within the Categories administration. Closing.
