### ISSUE TITLE
replace Admin page list with native tree (like categories)

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#64]
--orig 232 by craigh

Reported by: craigh  Owned by:  
Priority:  major  Milestone:  unassigned  
Version:  3.1.0  Keywords:  
Cc:  Guite, halbrooktech, mrtux, espaan, herr.vorragend, rallek, jusuff  Status:  pending-review  

Description ¶
  phenomenon¶
The newest implementation of the Category tree (in the category) module is quite nice and I think it might be a good idea to move the Content admin page view to this model. All the current functionality could be easily maintained I believe, although the look would be different. There would be no columnar display as there is now, just a tree view. The upside would be that the page wouldn't have to reload every time you change something and it would be using zikula-native tech.

I would like some feedback on this. I also probably would need help with implementation from Jusuff (who is pretty darned busy). So this may have to wait until the next version...

Attachments

Change History
comment:1 Changed 5 months ago by espaan 
    Interesting. Although I think the column structure with info and active/menu iconbuttons is highly appreciated by users. Of course a non-reloading would be nice, but that
also means that all pages are loaded in the page list. For some projects this could be a lot. So for me I would vote for keeping the current tree.

comment:2 Changed 5 months ago by mrtux 
    I don't know the Zikula 1.3 category stuff, but in the content module it's not just the tree. The meta information and toggles are also very important.

comment:3 Changed 5 months ago by craigh 
    all pages are not loaded now? what happens?

please look at the new (1.3) category module interface. and then comment.

as I said, all the current functionality would need to be maintained.

comment:4 Changed 5 months ago by jusuff 
    I think that tree view in main content view is good idea.
Content has tree-like structure so it would be quite natural to implement there tree view. All other is the matter of interface.
If loading all pages each time would be some problem - zikula javascript tree class could be extended and customised to load items on expanding via ajax. This would require more work - but it's possible to be done.

comment:5 Changed 5 months ago by espaan 
    As long as we can keep the current functionality with displaying the information than I would agree with a new tree implementation as well. 
I don't know if loading in all pageinfo would (since you display dynamically) slow down things. It might be very doable with the new zk ui tree implementation. 

Last edited 5 months ago by espaan (previous) (diff)

**Comment by Guite** [comment]
Version 5.0.0 offers both a table-based view as well as a jsTree based management page for the nested set(s). Closing.
