### ISSUE TITLE
Make functionality or a plugin with a partial display and readmore (like News)

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#68]
--orig 242

Reported by: espaan  Owned by:  
Priority:  minor  Milestone:  4.1.0  
Version:  GIT 4.x  Keywords:  
Cc:   Status:  pending-review  

Description ¶
  phenomenon¶
See also  http://support.zikula.de/index.php?module=CMS_Support_Forum&func=viewtopic&topic=30721 in german that is.
The request is to use Content, but sort of similar to News with a partial display of the Page or ContentItem? and a "read more" link for the full article. This would give website users the chance to use only Content and still use a News kind of display on the Start page.

reason¶
Content could be the only module used on a website and replace News for simple article usage.

recommendation¶
FInd a way to implement the above

**Comment by Guite** [comment]
Closing, because in Content 5.0.0 you can use the extended list for this which shows the first content element for each page. So this would be adequate for the requirement above if you add a teaser element for example.
