### ISSUE TITLE
Versioning: show differences

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#69]
-- orig 243

Reported by: pnFilip  Owned by:  
Priority:  major  Milestone:  4.1.0  
Version:  GIT 4.x  Keywords:  versions  
Cc:   Status:  pending-review  

Description ¶
  It would be great to have the option to show the differences between 2 versions of a page, like in the Cozi tracker, additions in green and deletions in red.

Reason¶
It is painful to read all available versions of a page in order to point their differences.

Small patch¶
in the file "templates/admin/history.tpl" line 30, please correct the date format modifier like: {$version.date|dateformat:'datetimebrief'}

**Comment by Guite** [comment]
Done.
