### ISSUE TITLE
Make a mailz plugin

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#71]
--orig 246

Reported by: espaan  Owned by:  
Priority:  minor  Milestone:  3.2.2  
Version:  GIT 3.x  Keywords:  
Cc:   Status:  pending-review  

Description ¶
  phenomenon¶
The mailz newsletter uses a plugin system to include new content/articles in the newslettern. Content could also provide somehting like that based on the last created pages. 

reason¶
Newsletter functionality for Content

recommendation¶
Check out the mailz api plugin in News and implement somthing similar in Content

Attachments

Change History
comment:1 Changed 3 months ago by espaan 
    See also:  https://github.com/zikula-modules/News/blob/master/src/modules/News/lib/News/Api/Mailz.php

of the code of the News26x version for zkcore12x

comment:2 Changed 3 months ago by craigh 
    is Mailz even 1.3 compatible?

comment:3 Changed 3 months ago by espaan 
    Not sure to be honest. It might very well be compatible. So that is why I listed it for 3.2.x release at first.

comment:4 Changed 3 months ago by craigh 
    I thought dev on the 3.2.x branch would end at 3.2.1 ;-)

**Comment by Guite** [comment]
As Content 5.0 is based on MOST a mailz plugin will automatically become available as soon (if) Mailz becomes ready for 2.0 so its support can be migrated in the generator, too. Closing.
