### ISSUE TITLE
remove use of Portal.js and replace with Zikula native libs

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#73]
--orig 253

Reported by: craigh  Owned by:  
Priority:  major  Milestone:  4.1.0  
Version:  GIT 4.x  Keywords:  
Cc:  jusuff  Status:  pending-review  

Description ¶
  remove use of Portal.js and replace with Zikula native libs

I'm hoping jusuff can do this for us for the next version :-D

Attachments

Change History
comment:1 Changed 2 months ago by espaan 
    Would be great yes ! The portal is an older JS files and difficult to maintain and extend.

comment:2 Changed 2 months ago by jusuff 
    I would be pleased to take care of this, but right now I can not say when I will be able do this. For sure not in next 2-4 weeks.

comment:3 Changed 2 months ago by craigh 
    I was hoping sometime in the next 3-6 months :-)

comment:4 Changed 2 months ago by jusuff 
    Uff - I was afraid that this is something urgent :) Then I can take this ticket.

**Comment by Guite** [comment]
Closed in favour of / included into #209
