### ISSUE TITLE
customer template service

### ISSUE THREAD

**Issue by espaan** [zikula-modules/Content#75]
--orig 257

Reported by: rallek  Owned by:  
Priority:  blocker  Milestone:  4.1.0  
Version:  GIT 4.x  Keywords:  
Cc:  guite  Status:  pending-review  

Description ¶
  phenomenon¶
today it is not possible to add a custom template. After updating content it has gone

reason¶
Util.php (and others?) are overwritten after updating

recommendation¶
images (preview) and other files are not found in the template folder of the theme or in /config. Look for a solution which do not overwrite files after updateing and place the files all at a place where they will be found by the template folder of the theme.

Please do this before official publishing content for 1.3.x core!

Attachments

Change History
comment:1 Changed 6 weeks ago by craigh 
    perhaps it is a language translation problem here, but I don't understand what you are trying to say.

As I understood it, it never was possible to add custom templates directly as it was possible with ContentTypes? - e.g. adding them to a module, etc.

it has always been required that custom templates be added to the Content module directly. this is still the case. But because the loading mechanism has changed, there is no auto-recognition of templates (or of ContentType? for that matter). You must register them in the event listener.

comment:2 follow-up: ↓ 3 Changed 6 weeks ago by espaan 
    I think Craig is right here. Templates need to be placed inside Content. What indeed has changed is that the recognition of layouttemplates (and contenttypes) is not done with a directory scan any more, but with the new event system. New templates therefore have to be added to the list that Content supplies.
If you add a new template inside Content you can add them to the list in 
 https://github.com/zikula-modules/Content/blob/master/src/modules/Content/lib/Content/Util.php

But indeed with an upgrade you lose the newly added template again. I do realize that this is different than before and we have to think of a way to circumvent this in some way.

comment:3 in reply to: ↑ 2 Changed 6 weeks ago by rallek 
    Replying to espaan:

But indeed with an upgrade you lose the newly added template again. I do realize that this is different than before and we have to think of a way to circumvent this in some way.

This exactly my concern. In the past it was possible to add my own templates. They are still working after an upgrade. I have placed several customized and own templates in my current site. My proposal is now to have an official way how to add own templates.

An idea as a compromize is to add a service for an additional optional file e.g. Util-site.php, which is not in the package. In the package you can deliver Util-site-example.php. That shows how the Util-site.php should look like.

But I would prefer to add the whole package of files outside of content e.g. at /config/content/... Than a clean way for an upgrade is possible (deleting old /modules/Content and add the upgrade package).

comment:4 Changed 6 weeks ago by craigh 
    ■Milestone changed from 4.0.0 to 4.1.0 
The old method is no longer available. we'll need to come up with something else. I don't see that happening before release of this version. I can tell you that when I was working on this area, I worked very hard to implement something like you are requesting and it was quite difficult. I think there are some ideas in my head that I hadn't considered then that might work, but again - not in 4.0.0. I would like to get this out ASAP. One thing that does need to be done is documenting how it can be accomplished currently.

comment:5 Changed 6 weeks ago by espaan 
    I agree, when 1.3 is out a 400 Content version should follow closely. For basic usage (so no personal templates) it all works ok. For 410 we have to think of a way to have the old behavior again. 
I was also thinking of a Util-personal.php kind of way. To check if that file is there. But I agree that it would be nice to place personal or personalized templates outside Content as an addition or override. 
But as Craig said this is quite hard in the layout/templating system in Content. It is by far not a simple template override. 

The major difference with the past is that with directory scanning you just add a template and it works out of the box, with the new Util.php method for Events at least one extra step is needed. Maybe an inline help message could be made somewhere in the admin settings on personal templates. Or a path where personal templates can be found??

**Comment by Guite** [comment]
Something like this will be part of #209. Closing in favour of that one.
