### ISSUE TITLE
Add a Comment/Note function

### ISSUE THREAD

**Issue by PhilBau** [zikula-modules/Content#77]
Used as a collaborative editing tool, a cool feature would be to add a "Insert Note/Comment" function to each ContentType added on a page. Clicking on "Add comment" opens a modal window where you can enter your comments and when you leave your pointer on "Comments (x)" you can read the comments.
Or an other solution would be the use of a hook to "EZComment".
Great tool, thanks!!

**Comment by Guite** [comment]
Content 5.0 provides the ability to add UI hooks not only to complete pages, but also to single content items. Will be reviewed/checked as part of #194.
