### ISSUE TITLE
flickr API seems to be changed

### ISSUE THREAD

**Issue by rallek** [zikula-modules/Content#97]
http://www.flickr.com/groups/api/discuss/72157629875546601/#comment72157629880647693

I do not know how to get the api-key running. There is a key and a private key provided. Which one I have to take? Or is the old key needed for the plugin? 

Documentation might be also a solution ;-)

**Comment by Guite** [comment]
The Flickr content type won't be migrated to Content 5.0. A better choice is the Flickr media type in the media module which is going to provide a generic media content type soon (see https://github.com/cmfcmf/MediaModule/issues/2 for reference). Closing as won't fix.
